name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

# [vars.BASIC_AUTH]
# Defined via the Cloudflare portal to avoid committing secrets.
# Make sure deployed version has JSON object with keys for each user.
# E.g. {"user": "Passwordfortheuser"}

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "f.adamcbloom.com"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "302dafa9d538485687f321458f270681"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://f.adamcbloom.com"

# url to repo, displayed in the index page
REPO = "https://github.com/illgitthat/pastebin-worker"

# url to the favicon
FAVICON = "https://sharzy.in/favicon-32x32.png"

# the name displayed in TOS
TOS_MAINTAINER = "Adam"

# the email displayed in TOS
TOS_MAIL = "pb@adamcbloom.com"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
